name: pocket_github
description: A pocket version of github.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: 3.10.5

dependencies:
  bloc: 8.1.2
  flutter_bloc: 8.1.3
  provider: 6.0.5
  equatable: 2.0.5
  meta: 1.9.1
  http: 1.1.0
  intl: 0.18.1
  get_it: 7.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  bloc_test: 9.1.3
  mocktail: 0.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
